### PR TITLE
Experimental: Add support for concurrent handler processing

### PR DESCRIPTION
**Pull request by jorangreef**
Add CONCURRENCY, KAFKA_BATCH_COUNT and KAFKA_BATCH_TIMEOUT constants.
These are hardcoded just for performance testing to sidestep any stale config issues.

TODO: Add guard against setTimeout calls to _consumeRecursive().

### CODE REVIEW

**Comment by jorangreef** [comment]
Hey @mdebarros and @donchangfoot, this is our first-run PR for performance testing verification.

If this works, we can do another PR to remove the hardcoded constants and expose concurrency as a first-class handler config option.

**Comment by mdebarros** [comment]
> Hey @mdebarros and @DonChangfoot, this is our first-run PR for performance testing verification.
> 
> If this works, we can do another PR to remove the hardcoded constants and expose concurrency as a first-class handler config option.

Hey @jorangreef, thanks for the PR. 

I am excited to verify this PR on the performance stream. Please ensure that the PR's target branch points to `release/9.5.1-performance`.

**Comment by jorangreef** [comment]
Thanks @mdebarros!

Face palm, I have updated the target branch to `release/9.5.1.-performance`.

**Comment by mdebarros** [comment]
> Thanks @mdebarros!
> 
> Face palm, I have updated the target branch to `release/9.5.1.-performance`.

Thanks!

**Pull request merged**
